/*
 *
 * PhanQuyen constants
 *
 */

export const DEFAULT_ACTION = "app/QLDeXuat/DEFAULT_ACTION";
export const GET_DEXUAT_ACTION = "app/QLDeXuat/GET_DEXUAT_ACTION";
export const GET_DEXUAT_ACTION_SUCCESS = "app/QLDeXuat/GET_DEXUAT_ACTION_SUCCESS";
export const GET_DEXUAT_ACTION_ERROR = "app/QLDeXuat/GET_DEXUAT_ACTION_ERROR";
export const GET_DEXUAT_CHITIET_ACTION = "app/QLDeXuat/GET_DEXUAT_CHITIET_ACTION";
export const GET_DEXUAT_CHITIET_SUCCESS = "app/QLDeXuat/GET_DEXUAT_CHITIET_ACTION_SUCCESS";
export const GET_DEXUAT_CHITIET_ERROR = "app/QLDeXuat/GET_DEXUAT_CHITIET_ACTION_ERROR";
