//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TEMIS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaoVe_NCS
    {
        public long Id { get; set; }
        public Nullable<int> Buoc1 { get; set; }
        public Nullable<int> Buoc2 { get; set; }
        public Nullable<int> Buoc3 { get; set; }
        public Nullable<int> Buoc4 { get; set; }
        public Nullable<int> Buoc5 { get; set; }
        public Nullable<int> Buoc6 { get; set; }
        public Nullable<int> Buoc7 { get; set; }
        public string MaNCS { get; set; }
        public Nullable<int> Status { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
    }
}
