//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TEMIS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaoVeCapTruong
    {
        public long Id { get; set; }
        public Nullable<int> HinhThuc { get; set; }
        public string File { get; set; }
        public string SoQD { get; set; }
        public Nullable<System.DateTime> NgayKy { get; set; }
        public string HoTen { get; set; }
        public string CoquanCT { get; set; }
        public string VaiTro { get; set; }
        public string TenLanBV { get; set; }
        public string GioBV { get; set; }
        public Nullable<System.DateTime> NgayBV { get; set; }
        public string DiaDiem { get; set; }
        public Nullable<bool> KetQua { get; set; }
        public string MaNCS { get; set; }
        public string TenGiayTo { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> Type { get; set; }
    }
}
