//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TEMIS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChuyenDe
    {
        public long Id { get; set; }
        public string TenCD { get; set; }
        public Nullable<int> TinChi { get; set; }
        public Nullable<System.DateTime> NgayBV { get; set; }
        public Nullable<double> DiemSo { get; set; }
        public string File { get; set; }
        public string HoTen { get; set; }
        public string CoQuanCT { get; set; }
        public string VaiTro { get; set; }
        public string UserId { get; set; }
    }
}
