//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TEMIS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CongTrinhKhoaHoc
    {
        public int Id { get; set; }
        public string NamCB { get; set; }
        public string TenCTKH { get; set; }
        public string TenTapChi { get; set; }
        public string NoiXB { get; set; }
        public string File { get; set; }
        public string VaiTro { get; set; }
        public string HinhThuc { get; set; }
        public string MaNCS { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> Type { get; set; }
    }
}
