//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TEMIS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DangKyTuyenSinh
    {
        public long Id { get; set; }
        public string HoTen { get; set; }
        public string GioiTinh { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string SoDienThoai { get; set; }
        public string Email { get; set; }
        public string NoiSinh { get; set; }
        public string DiaChiLienLac { get; set; }
        public string NgheNghiep { get; set; }
        public string CoQuanCongTacHienNay { get; set; }
        public string NamBatDauCongTac { get; set; }
        public string HienLaCanBo { get; set; }
        public string ViTriConViecHienTai { get; set; }
        public string ThamNiemNghieNghiep { get; set; }
        public string ChuyenMon { get; set; }
        public string Truong_TN_DaiHoc { get; set; }
        public Nullable<int> Nam_TN_DaiHoc { get; set; }
        public string HeDaoTao_DaiHoc { get; set; }
        public string Nghanh_TN_DaiHoc { get; set; }
        public string DiemTrungBinh_DaiHoc { get; set; }
        public string LoaiTotNghiep_DaiHoc { get; set; }
        public string Url_FileUpload_DaiHoc { get; set; }
        public string Truong_TN_ThacSi { get; set; }
        public string Nam_TN_ThacSi { get; set; }
        public string HeDaoTao_ThacSi { get; set; }
        public string Nghanh_TN_ThacSi { get; set; }
        public string DiemTrungBinh_ThacSi { get; set; }
        public string Url_FileUpload_ThacSi { get; set; }
        public string NgoaiNgu { get; set; }
        public string LoaiVanBangNgoaiNgu { get; set; }
        public string Url_ChungChiNgoaiNgu { get; set; }
        public string BoTucKienThuc { get; set; }
        public int ChuyenNghanhDuTuyenId { get; set; }
        public string TenChuyenNghanhDuTuyen { get; set; }
        public string DoiTuongDuTuyen { get; set; }
        public string ThoiGianHinhThucDaoTao { get; set; }
        public Nullable<int> Status { get; set; }
        public string TenDeTai { get; set; }
        public Nullable<int> KhoaId_NHD1 { get; set; }
        public Nullable<int> Id_NHD1 { get; set; }
        public string NHD1 { get; set; }
        public Nullable<int> KhoaId_NHD2 { get; set; }
        public Nullable<int> Id_NHD2 { get; set; }
        public string NHD2 { get; set; }
        public string CoQuanCongTac_NHD2 { get; set; }
        public string NoiDungPhanHoi { get; set; }
        public string TepFilePhanHoi { get; set; }
        public string MaNCS { get; set; }
        public string Truong_TN_VB2 { get; set; }
        public Nullable<int> Nam_TN_VB2 { get; set; }
        public string HeDaoTao_VB2 { get; set; }
        public string Nganh_TN_VB2 { get; set; }
        public string LoaiTotNghiep_VB2 { get; set; }
        public string Url_FileUpload_VB2 { get; set; }
        public string DiemTrungBinh_VB2 { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<bool> CapQuyenTruyCap { get; set; }
        public string SoCMND { get; set; }
        public Nullable<System.DateTime> Ngaycap_CMND { get; set; }
        public string Noicap_CMND { get; set; }
        public string TinhThanh_CMND { get; set; }
        public string Quan_CMND { get; set; }
        public string Xa_CMND { get; set; }
        public string Url_FileUpload_AnhSoYeuLyLich { get; set; }
        public string Url_FileUpload_CongVanGioiThieu { get; set; }
        public string Url_FileUpload_GiaySucKhoe { get; set; }
        public string Url_FileUpload_HopDongLaoDong { get; set; }
        public string Url_FileUpload_ThuGioiThieu { get; set; }
        public string Url_FileUpload_BaiBaoKhoaHoc { get; set; }
        public string Url_FileUpload_DeCuongNghienCuu { get; set; }
        public string Url_FileUpload_Zip { get; set; }
        public string TenNganh { get; set; }
        public string TenKhoa { get; set; }
        public Nullable<int> NganhId { get; set; }
        public Nullable<int> KhoaId { get; set; }
        public Nullable<int> IdDotTS { get; set; }
        public string DanToc { get; set; }
        public Nullable<int> TrangThaiTuyenSinh { get; set; }
        public Nullable<double> DiemDeCuong { get; set; }
        public Nullable<double> DiemTong { get; set; }
    }
}
