//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TEMIS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DanhSachCanBoAddForm
    {
        public int Id { get; set; }
        public Nullable<int> IdCanBo { get; set; }
        public string TenCanBo { get; set; }
        public string ChucVu { get; set; }
        public string VaiTro { get; set; }
        public Nullable<int> IdBieuMau { get; set; }
        public string HocHamHocVi { get; set; }
        public string CoQuanCongTac { get; set; }
        public Nullable<int> IdKhoa { get; set; }
        public string TenKhoa { get; set; }
        public Nullable<int> IdKhoahoc { get; set; }
        public Nullable<int> IdDotTS { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<int> IdKhoaSelected { get; set; }
        public Nullable<int> IdChuyenNganh { get; set; }
        public string TenChuyenNganh { get; set; }
    }
}
