//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TEMIS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DanhSachChuyenDe
    {
        public long Id { get; set; }
        public string TenChuyenDe { get; set; }
        public Nullable<int> SoTinChi { get; set; }
        public Nullable<System.DateTime> NgayBaoVe { get; set; }
        public Nullable<double> DiemSo { get; set; }
        public string MaNCS { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
    }
}
