//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TEMIS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiemTuyenSinh
    {
        public long Id { get; set; }
        public string SoBaoDanh { get; set; }
        public string MaPhong { get; set; }
        public Nullable<long> ThiSinhId { get; set; }
        public Nullable<int> Diem { get; set; }
        public string NguoiTao { get; set; }
    }
}
