//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TEMIS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HocPhi
    {
        public long Id { get; set; }
        public string UserName { get; set; }
        public string MaNCS { get; set; }
        public string File { get; set; }
        public Nullable<int> Khoa { get; set; }
        public string TenKhoa { get; set; }
        public int ChuyennNghanh { get; set; }
        public string TenChuyenNganh { get; set; }
        public Nullable<int> KhoaHoc { get; set; }
        public string TenKhoaHoc { get; set; }
        public string HoTen { get; set; }
        public string NoiDung { get; set; }
        public Nullable<int> TrangThai { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<double> MucNop { get; set; }
        public Nullable<int> Type { get; set; }
    }
}
