//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TEMIS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HocPhiNCS
    {
        public int Id { get; set; }
        public string MaHV { get; set; }
        public string Email { get; set; }
        public string HoTen { get; set; }
        public Nullable<double> TongTien { get; set; }
        public Nullable<double> DaTra { get; set; }
        public Nullable<bool> HoanThanh { get; set; }
        public Nullable<bool> QuaHan { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
    }
}
