//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TEMIS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HocPhan
    {
        public long Id { get; set; }
        public string TenHocPhan { get; set; }
        public Nullable<int> SoDVHT { get; set; }
        public Nullable<bool> DieuKien { get; set; }
        public Nullable<bool> TuChon { get; set; }
        public Nullable<int> SoTietLyThuyet { get; set; }
        public Nullable<int> SoTietThucHanh { get; set; }
        public string MaHocPhan { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<int> KhoaHocId { get; set; }
        public Nullable<int> KhoaId { get; set; }
        public Nullable<int> NganhId { get; set; }
        public Nullable<int> ChuyenNganhId { get; set; }
        public Nullable<int> SoTinChi { get; set; }
        public Nullable<int> LoaiHP { get; set; }
    }
}
