//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TEMIS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HocPhan_GiangVien
    {
        public int Id { get; set; }
        public Nullable<int> YearId { get; set; }
        public Nullable<int> GradeId { get; set; }
        public Nullable<int> ConversionId { get; set; }
        public Nullable<int> Departmentid { get; set; }
        public Nullable<int> ForDepartmentId { get; set; }
        public string Name { get; set; }
        public Nullable<double> LessionTime { get; set; }
        public string TeachingTime { get; set; }
        public string Class { get; set; }
        public Nullable<int> Size { get; set; }
        public Nullable<bool> Paid { get; set; }
        public string Course { get; set; }
        public string Desc { get; set; }
        public Nullable<bool> Invited { get; set; }
        public string Specializing { get; set; }
        public string InvitedPartner { get; set; }
        public string LinkedPartner { get; set; }
        public string SubjectName { get; set; }
        public Nullable<int> InvitedDegreeId { get; set; }
        public Nullable<int> StaffId { get; set; }
        public Nullable<int> SemesterId { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<long> IdHocPhan { get; set; }
        public Nullable<long> IdGiangVien { get; set; }
        public Nullable<int> LoaiGiangVien { get; set; }
        public Nullable<int> KhoaId { get; set; }
    }
}
