//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TEMIS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LuanAnTienSi
    {
        public int Id { get; set; }
        public string File { get; set; }
        public Nullable<int> Khoa { get; set; }
        public Nullable<int> KhoaHoc { get; set; }
        public string MaNCS { get; set; }
        public string HoTen { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public Nullable<int> Lop { get; set; }
        public Nullable<int> ChuyenNghanh { get; set; }
        public string NoiDung { get; set; }
        public Nullable<bool> TrangThai { get; set; }
        public string QDBVTruong { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
    }
}
