//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TEMIS.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TEMIS_systemEntities : DbContext
    {
        public TEMIS_systemEntities()
            : base("name=TEMIS_systemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<HocPhan_NCS> HocPhan_NCS { get; set; }
        public virtual DbSet<BieuMau> BieuMau { get; set; }
        public virtual DbSet<ChuongTrinhDaoTao> ChuongTrinhDaoTao { get; set; }
        public virtual DbSet<ChuyenMucVanBan> ChuyenMucVanBan { get; set; }
        public virtual DbSet<DanhMucThongTin> DanhMucThongTin { get; set; }
        public virtual DbSet<DanhMucTinTuc> DanhMucTinTuc { get; set; }
        public virtual DbSet<GiangVien> GiangVien { get; set; }
        public virtual DbSet<HocPhan> HocPhan { get; set; }
        public virtual DbSet<Khoa> Khoa { get; set; }
        public virtual DbSet<KhoaHoc> KhoaHoc { get; set; }
        public virtual DbSet<KhoaHoc_HocVien> KhoaHoc_HocVien { get; set; }
        public virtual DbSet<MonHoc> MonHoc { get; set; }
        public virtual DbSet<MucHocPhi> MucHocPhi { get; set; }
        public virtual DbSet<NCS> NCS { get; set; }
        public virtual DbSet<NganhDaoTao> NganhDaoTao { get; set; }
        public virtual DbSet<PhongThi> PhongThi { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<SysLog> SysLog { get; set; }
        public virtual DbSet<ThamSoBieuMau> ThamSoBieuMau { get; set; }
        public virtual DbSet<ThuVien> ThuVien { get; set; }
        public virtual DbSet<TinTuc> TinTuc { get; set; }
        public virtual DbSet<TruongThongTin> TruongThongTin { get; set; }
        public virtual DbSet<VanBan> VanBan { get; set; }
        public virtual DbSet<BaoVeCapBoMon> BaoVeCapBoMon { get; set; }
        public virtual DbSet<BaoVeCapTruong> BaoVeCapTruong { get; set; }
        public virtual DbSet<LuanAnTienSi> LuanAnTienSi { get; set; }
        public virtual DbSet<PhanBienDocLap> PhanBienDocLap { get; set; }
        public virtual DbSet<SauBaoVe> SauBaoVe { get; set; }
        public virtual DbSet<CongTrinhKhoaHoc> CongTrinhKhoaHoc { get; set; }
        public virtual DbSet<DanhSachChuyenDe> DanhSachChuyenDe { get; set; }
        public virtual DbSet<TieuBanChamChuyenDe> TieuBanChamChuyenDe { get; set; }
        public virtual DbSet<BaoVeTongQuan> BaoVeTongQuan { get; set; }
        public virtual DbSet<BaoVe_NCS> BaoVe_NCS { get; set; }
        public virtual DbSet<DanhSachHoiDong> DanhSachHoiDong { get; set; }
        public virtual DbSet<KetQuaBaoVe> KetQuaBaoVe { get; set; }
        public virtual DbSet<QuyetDinh> QuyetDinh { get; set; }
        public virtual DbSet<NguoiHuongDan> NguoiHuongDan { get; set; }
        public virtual DbSet<HoiDongPhanBienDocLap> HoiDongPhanBienDocLap { get; set; }
        public virtual DbSet<Diem> Diem { get; set; }
        public virtual DbSet<GiayToBaoVeLuanAn> GiayToBaoVeLuanAn { get; set; }
        public virtual DbSet<LichBaoVe> LichBaoVe { get; set; }
        public virtual DbSet<TruongThongTin_NCS> TruongThongTin_NCS { get; set; }
        public virtual DbSet<HoSoThamDinh> HoSoThamDinh { get; set; }
        public virtual DbSet<ThongTinDeTai> ThongTinDeTai { get; set; }
        public virtual DbSet<HocPhan_GiangVien> HocPhan_GiangVien { get; set; }
        public virtual DbSet<SysSetting> SysSetting { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<UserRoles> UserRoles { get; set; }
        public virtual DbSet<ChuyenNganhDaoTao> ChuyenNganhDaoTao { get; set; }
        public virtual DbSet<ThongBao> ThongBao { get; set; }
        public virtual DbSet<City> City { get; set; }
        public virtual DbSet<District> District { get; set; }
        public virtual DbSet<Ward> Ward { get; set; }
        public virtual DbSet<HocPhiNCS> HocPhiNCS { get; set; }
        public virtual DbSet<DotTuyenSinh> DotTuyenSinh { get; set; }
        public virtual DbSet<SysNotification> SysNotification { get; set; }
        public virtual DbSet<HocPhi> HocPhi { get; set; }
        public virtual DbSet<SysComment> SysComment { get; set; }
        public virtual DbSet<DangKyTuyenSinh> DangKyTuyenSinh { get; set; }
        public virtual DbSet<DanhSachCanBoAddForm> DanhSachCanBoAddForm { get; set; }
        public virtual DbSet<DanToc> DanToc { get; set; }
    }
}
