//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TEMIS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MonHoc
    {
        public int Id { get; set; }
        public string MaMon { get; set; }
        public string TenMon { get; set; }
        public Nullable<int> HocPhanId { get; set; }
        public Nullable<int> KhoaHocId { get; set; }
        public Nullable<int> KhoaId { get; set; }
        public Nullable<int> NganhId { get; set; }
        public Nullable<int> ChuyenNganhId { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
    }
}
