//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TEMIS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MucHocPhi
    {
        public int Id { get; set; }
        public string MaKhoa { get; set; }
        public string TenKhoa { get; set; }
        public string NamHoc { get; set; }
        public Nullable<double> HocPhi { get; set; }
        public string MaNganh { get; set; }
        public string TenNganh { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
    }
}
