//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TEMIS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class NCS
    {
        public long Id { get; set; }
        public string Ma { get; set; }
        public string HoTen { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string NoiSinh { get; set; }
        public string HoKhau { get; set; }
        public string DiaChi { get; set; }
        public string DienThoai { get; set; }
        public string Email { get; set; }
        public string GioiTinh { get; set; }
        public string DanToc { get; set; }
        public Nullable<int> ChucDanhId { get; set; }
        public Nullable<int> KhoaId { get; set; }
        public string QuocTich { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<int> KHoaHocId { get; set; }
        public Nullable<int> NganhId { get; set; }
        public Nullable<int> NganhDaoTaoId { get; set; }
    }
}
