//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TEMIS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhongThi
    {
        public long Id { get; set; }
        public string MaPhongThi { get; set; }
        public Nullable<int> MaNghanh { get; set; }
        public string ChuyenNghanh { get; set; }
        public string NgoaiNgu { get; set; }
        public string LoaiThiSinh { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
    }
}
