//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TEMIS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThamSoBieuMau
    {
        public int Id { get; set; }
        public string TenThamSo { get; set; }
        public string GiaTriThamSo { get; set; }
        public string KieuDuLieu { get; set; }
        public string CauTrucHienThi { get; set; }
        public Nullable<int> ThuTuHienThi { get; set; }
        public string BieuMau { get; set; }
        public Nullable<int> BieuMauId { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
    }
}
