//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TEMIS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThongTinDeTai
    {
        public long Id { get; set; }
        public string TenDeTai { get; set; }
        public string SoQuyetDinh { get; set; }
        public Nullable<System.DateTime> NgayKy { get; set; }
        public string FileKiemChung { get; set; }
        public string MaNCS { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public string NHD1 { get; set; }
        public string NHD2 { get; set; }
        public string NhomBaoCao { get; set; }
        public Nullable<System.DateTime> NgayHop { get; set; }
        public string GioHop { get; set; }
        public string DiaDiem { get; set; }
    }
}
