//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TEMIS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThuVien
    {
        public long Id { get; set; }
        public Nullable<int> KhoaId { get; set; }
        public Nullable<int> KhoaHocId { get; set; }
        public Nullable<int> NganhId { get; set; }
        public Nullable<int> ChuyenNganhId { get; set; }
        public string HoTen { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public Nullable<bool> NopLan1 { get; set; }
        public string UrlFileLan1 { get; set; }
        public Nullable<bool> NopLan2 { get; set; }
        public string UrlFileLan2 { get; set; }
        public Nullable<System.DateTime> QDBV_CapTruong { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public string MaNCS { get; set; }
    }
}
