//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TEMIS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VanBan
    {
        public int Id { get; set; }
        public string TieuDe { get; set; }
        public string URL { get; set; }
        public Nullable<int> ChuyenMuc { get; set; }
        public string DauMuc { get; set; }
        public string Anh { get; set; }
        public Nullable<int> HinhThuc { get; set; }
        public Nullable<bool> TrangThai { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
    }
}
