/*
 *
 * PhanQuyen constants
 *
 */

export const DEFAULT_ACTION = "app/QLDETAI/DEFAULT_ACTION";
export const GET_DETAI_ACTION = "app/QLDETAI/GET_DETAI_ACTION";
export const GET_DETAI_ACTION_SUCCESS = "app/QLDETAI/GET_DETAI_ACTION_SUCCESS";
export const GET_DETAI_ACTION_ERROR = "app/QLDETAI/GET_DETAI_ACTION_ERROR";
export const GET_DETAI_CHITIET_ACTION = "app/QLDETAI/GET_DETAI_CHITIET_ACTION";
export const GET_DETAI_CHITIET_SUCCESS = "app/QLDETAI/GET_DETAI_CHITIET_ACTION_SUCCESS";
export const GET_DETAI_CHITIET_ERROR = "app/QLDETAI/GET_DETAI_CHITIET_ACTION_ERROR";
